import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from './../providers/theme-provider';
import  ConvexClientProvider  from "@/providers/convex-client-provider";
import { ClerkProvider } from '@clerk/nextjs';
import { SafeHydration } from "@/providers/SafeHydration";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ChatSphere",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
          <SafeHydration>
            <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange={true}>
            <ConvexClientProvider>
              <main className="w-screen h-screen flex">
                    {children}
                    <Toaster />
              </main>
              </ConvexClientProvider>
            </ThemeProvider>
          </SafeHydration>
        </body>
      </html>
    </ClerkProvider>
  );
}
